version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data: